Repository breadtubetv/breadtubetv, pull requests merged in 2019-01, with the labels that each got.

#8 Channels Refactor
  content/_redirects
  layouts/_default/baseof.html
  layouts/index.html
  layouts/partials/base/foot.html
  layouts/partials/base/head.html
  layouts/partials/base/navigation.html
  layouts/partials/base/sidebar.html
  layouts/partials/channels/card.html
  layouts/partials/channels/row.html
  layouts/partials/playlists/row.html
  layouts/partials/playlists/videos.html
  layouts/partials/videos/card.html
  layouts/playlists/list.html
  layouts/playlists/single.html
  static/img/channels/angiespeaks.jpg
  static/img/channels/commentiquette.jpg
  static/img/channels/contrapoints.jpg
  static/img/channels/democracyatwrk.jpg
  static/img/channels/democracynow.jpg
  static/img/channels/empirefiles.jpg
  static/img/channels/erincollective.jpg
  static/img/channels/friendlyjordies.jpg
  static/img/channels/hbomberguy.jpg
  static/img/channels/mexie.jpg
  static/img/channels/noncompete.jpg
  static/img/channels/petercoffin.jpg
  static/img/channels/ploppy111.jpg
  static/img/channels/radicalreviewer.jpg
  static/img/channels/samseder.jpg
  static/img/channels/shaun.jpg
  static/img/channels/somemorenews.jpg
  static/img/channels/thejuicemedia.jpg
  static/img/channels/thephilosophytube.jpg
  static/img/channels/theyoungturks.jpg
  static/img/channels/thoughtslime.jpg
  static/img/channels/threearrows.jpg
  static/img/channels/xaxie1.jpg
  static/img/channels/zerobooks.jpg
Labels: tech debt

#12 iFrame allowfullscreen
  layouts/partials/videos/card.html
Labels: enhancement

#13 Local CSS and Fonts
  layouts/partials/base/head.html
  static/css/bootstrap.min.css
  static/css/brands.min.css
  static/css/fontawesome.min.css
  static/webfonts/fa-brands-400.eot
  static/webfonts/fa-brands-400.svg
  static/webfonts/fa-brands-400.ttf
  static/webfonts/fa-brands-400.woff
  static/webfonts/fa-brands-400.woff2
Labels: enhancement

#15 Christoper Szabo
  data/channels.yml
  static/img/channels/christopherszabo.jpg
Labels: enhancement

#17 What are the values of an Anarchist Economy
  content/playlists/organizing.md
  data/channels.yml
  data/videos.yml
  static/img/channels/dirkkelly.jpg
Labels: enhancement

#18 Fix What Are Values
  data/videos.yml
Labels: bug

#21 Feature: Added in a couple of new channels
  data/channels.yml
  static/img/channels/hasanabi.jpg
  static/img/channels/kylekulinski.jpg
  static/img/channels/politicalvigilante.jpg
Labels: channels

#25 Creationist Cat
  data/channels.yml
  static/img/channels/creationistcat.jpg
Labels: channels

#26 Hakim
  data/channels.yml
  static/img/channels/hakim.jpg
Labels: channels

#27 Fix whitespace on Democratic Socialist 01
  data/channels.yml
Labels: bug

#32 Critique of Authority via @dextreFreeman
  content/playlists/authority.md
  data/channels.yml
  data/videos.yml
  static/img/channels/beauofthefifthcolumn.jpg
  static/img/channels/katblaque.jpg
Labels: channels, playlists

#11 Video Card Loads iFrame Modal
  layouts/partials/base/foot.html
  layouts/partials/videos/card.html
Labels: enhancement

#47 Sticky Navigation
  layouts/_default/baseof.html
  layouts/partials/base/navigation.html
  layouts/partials/base/sidebar.html
  layouts/partials/playlists/row.html
  static/css/site.css
Labels: user experience

#53 no max width on channels
  static/css/site.css
Labels: needs-review

#57 Redirects for Social
  config.toml
  content/_redirects
Labels: enhancement, good first issue, needs review, xp user

#55 Channel Card Needs Max Width
  static/css/site.css
Labels: data channels, good first issue, needs review, xp user

#56 Providers Data Structure. Patreon & YouTube
  data/channels/anactualjoke.yml
  data/channels/anarchopac.yml
  layouts/partials/channels/card.html
Labels: data channels, enhancement, needs review, xp dev

#52 Channel and Playlist Suggestion Form
  config.toml
  content/channels/new.md
  content/playlists/new/index.md
  layouts/channels/single.html
  layouts/partials/base/navigation.html
  layouts/partials/channels/new.html
  layouts/partials/playlists/new.html
  layouts/playlists/single.html
  static/css/site.css
Labels: data channels, enhancement, needs review, xp creator, xp user

#65 New Content
  content/playlists/anarchist-revolution-syria.md
  data/channels/cultofdusty.yml
  data/channels/jose.yml
  data/channels/letstalkaboutstuff.yml
  data/channels/perseus999.yml
  data/channels/realmedia.yml
  data/videos.yml
  static/img/channels/cultofdusty.jpg
  static/img/channels/letstalkaboutstuff.jpg
  static/img/channels/perseus999.jpg
  static/img/channels/realmedia.jpg
Labels: data channels, data playlists, needs review
