Repository breadtubetv/breadtubetv, pull requests merged in 2019-06, with the labels that each got.

#293 Channel Submission Comments
  layouts/partials/channels/edit.html
  layouts/partials/channels/new.html
Labels: content/channels, needs review, xp/creator, xp/developer, xp/user

#297 Remove Forestry Config
  .forestry/front_matter/templates/pages.yml
  .forestry/front_matter/templates/playlist.yml
  .forestry/settings.yml
Labels: needs review, xp/developer

#298 README Update Content/Channel Dir
  README.md
  content/channel/revolutiontube.md
  content/channel/therealnewsnetwork.md
Labels: needs review, xp/developer

#277 Hardcore Lime
  content/hardcorelime.md
  data/channels/hardcorelime.yml
  data/videos/hardcorelime/C7hQQhKxaL8.yml
  data/videos/hardcorelime/ZFBilhX_QyQ.yml
  data/videos/hardcorelime/kPyC2rExRDc.yml
  data/videos/hardcorelime/rDL0V6mYlVY.yml
  data/videos/hardcorelime/u-o6CwdRHgM.yml
  data/videos/hardcorelime/x0YvJWwx7fE.yml
  data/videos/hardcorelime/zngm2KqLhbk.yml
  static/img/channels/hardcorelime.jpg
Labels: content/channels, content/video, needs review, xp/creator, xp/user

#282 Permissions Change: Admins Merge on data and content
  .github/settings.yml
Labels: Discussion, needs review

#274 Vaush content update
  content/channel/vaush.md
  data/channels/vaush.yml
  data/videos/vaush/-94STO1-D5Q.yml
  data/videos/vaush/4CZUNd-N1ko.yml
  data/videos/vaush/BHQapW0HzEw.yml
  data/videos/vaush/JlJkVPn2NRM.yml
Labels: content/video, needs review, xp/user

#299 Mexie Content
  content/_index.md
  content/channel/mexie.md
  data/channels/mexie.yml
  data/videos/mexie/EwModqyLzQE.yml
  data/videos/mexie/HIaFfhRB15s.yml
  data/videos/mexie/MkLC3XyqrEY.yml
  data/videos/mexie/OYuo2QdNu88.yml
  data/videos/mexie/VEKUVff7fLk.yml
  data/videos/mexie/WcLelEGYQGM.yml
  data/videos/mexie/ZjsvG595Gf8.yml
  data/videos/mexie/czJ9dYoHaZc.yml
  data/videos/mexie/dm1YphXia1M.yml
  data/videos/mexie/oY_Dt1jey4M.yml
  data/videos/mexie/u80OmT2_zyA.yml
  data/videos/mexie/zsRR6zbuQLA.yml
Labels: content/channels, content/video, enhancement, needs review, xp/creator, xp/user

#300 Literally Garbage
  content/_index.md
  content/channel/literallygarbage.md
  data/channels/literallygarbage.yml
  data/videos/literallygarbage/2JB9BA9V5aI.yml
  data/videos/literallygarbage/EPBCd1GkYh0.yml
  data/videos/literallygarbage/UG70ZTAFGx8.yml
  data/videos/literallygarbage/VIXksTpJS98.yml
  data/videos/literallygarbage/c8d4QkfMcfs.yml
  data/videos/literallygarbage/cG3o52hGGD8.yml
  data/videos/literallygarbage/gxVoLbNU0a8.yml
  data/videos/literallygarbage/j3Es8ai227w.yml
  data/videos/literallygarbage/m4dfYc96GPs.yml
  data/videos/literallygarbage/mD6LQpP7GZc.yml
  data/videos/literallygarbage/qUxCXckcBcU.yml
  data/videos/literallygarbage/y3FtNkzBIsk.yml
  static/img/channels/literallygarbage.jpg
Labels: content/channels, content/video, needs review, xp/creator, xp/user

#301 removed some more from home, added to this week
  content/_index.md
  content/playlists/this-week.md
Labels: needs review, xp/user

#248 About Page
  content/_index.md
  content/_redirects
  content/about/_index.md
  content/privacy/_index.md
  layouts/page/list.html
  layouts/partials/base/footer.html
  static/css/breadtube.css
Labels: needs review, xp/user

#305 The People's Bayonet
  content/channel/thepeoplesbayonet.md
  data/channels/thepeoplesbayonet.yml
  data/videos/thepeoplesbayonet/1ML8qCNCcJ0.yml
  data/videos/thepeoplesbayonet/2vAEeK67lSE.yml
  data/videos/thepeoplesbayonet/CmoutCc8XSk.yml
  data/videos/thepeoplesbayonet/MgWwMGPveC4.yml
  data/videos/thepeoplesbayonet/NhYbfOI8rfI.yml
  data/videos/thepeoplesbayonet/TUUs8dzDlco.yml
  data/videos/thepeoplesbayonet/lC83WlZd6PU.yml
  data/videos/thepeoplesbayonet/mTQAIO70ZZA.yml
  data/videos/thepeoplesbayonet/oO8MiZxpNrE.yml
  data/videos/thepeoplesbayonet/qPvpnVTv54E.yml
  data/videos/thepeoplesbayonet/ruoxWMv00NI.yml
  static/img/channels/thepeoplesbayonet.jpg
Labels: content/channels, content/video, needs review, xp/creator, xp/user

#304 Just Wondering Update
  content/channel/justwondering.md
  data/channels/justwondering.yml
  data/videos/justwondering/F1tEzTOHPDY.yml
Labels: content/channels, content/video, needs review, xp/creator, xp/user

#303 dirkkelly update
  content/channel/dirkkelly.md
  data/channels/dirkkelly.yml
  data/videos/dirkkelly/-NCCYXrZBho.yml
  data/videos/dirkkelly/9gvkwp4uPc0.yml
  data/videos/dirkkelly/U9Oao0NOs7s.yml
  data/videos/dirkkelly/wqpTO6rrajk.yml
Labels: content/channels, content/video, needs review, xp/creator, xp/user

#309 Update angiespeaks.yml
  data/channels/angiespeaks.yml
Labels: bug

#308 Fix github redirect
  content/_redirects
Labels: bug

#310 Update how-anarchism-works.md
  content/playlists/how-anarchism-works.md
Labels: bug

#311 Update anactualjoke.yml
  data/channels/anactualjoke.yml
Labels: content/channels, needs review

#312 Update mexie.yml
  data/channels/mexie.yml
Labels: needs review

#313 Update jose.yml
  data/channels/jose.yml
Labels: needs review

#315 Update faradayspeaks.yml
  data/channels/faradayspeaks.yml
Labels: needs review

#316 Update polidice.yml
  data/channels/polidice.yml
Labels: needs review

#319 Update tmbs.yml
  data/channels/tmbs.yml
Labels: needs review

#321 Update thenewsymbolization.yml
  data/channels/thenewsymbolization.yml
Labels: needs review

#322 Update erincollective.yml
  data/channels/erincollective.yml
Labels: needs review

#320 Update stimulator.yml
  data/channels/stimulator.yml
Labels: needs review

#323 Update sarcasmitron.yml
  data/channels/sarcasmitron.yml
Labels: needs review

#324 Update rebeccawatson.yml
  data/channels/rebeccawatson.yml
Labels: needs review

#325 Update thefinnishbolshevik.yml
  data/channels/thefinnishbolshevik.yml
Labels: needs review

#326 Update sarahz.yml
  data/channels/sarahz.yml
Labels: needs review

#327 Update lunaoi.yml
  data/channels/lunaoi.yml
Labels: needs review

#328 Update shaun.yml
  data/channels/shaun.yml
Labels: needs review

#329 Update tmm.yml
  data/channels/tmm.yml
Labels: needs review

#330 Update rotfrontgaming.yml
  data/channels/rotfrontgaming.yml
Labels: needs review

#331 Update brotherneuro.yml
  data/channels/brotherneuro.yml
Labels: needs review

#332 Update jaydeeforrester.yml
  data/channels/jaydeeforrester.yml
Labels: needs review

#317 Update andrejpskraba.yml
  content/channel/andrejpskraba.md
  data/channels/andrejpskraba.yml
  static/img/channels/andrejpskraba.jpg
Labels: Discussion, needs review

#314 Update inotterwords.yml
  data/channels/inotterwords.yml
Labels: needs review

#318 Update mariathewitch.yml
  content/channel/mariajorge.md
  content/channel/mariathewitch.md
  data/channels/mariajorge.yml
  data/channels/mariathewitch.yml
  static/img/channels/mariajorge.jpg
Labels: help wanted, needs review
